# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/prestadiario_db

# Security & JWT Configuration
prestadiario.jwt.secret=cobro_diario_secret_key_spring_boot_mongodb_react_tailwind_application_secret_key_2026_minimum_256_bits
prestadiario.jwt.expirationMs=86400000

# Logging Properties
logging.level.org.springframework.web=INFO
logging.level.com.cobro.prestadiario=DEBUG
